cat /usr/share/doc/libpam-runtime/copyright                                        > libpam-runtime.txt                 
cat /usr/share/doc/libpam0g/copyright                                              > libpam0g.txt                       
cat /usr/share/doc/base-passwd/copyright                                           > base-passwd.txt                    
cat /usr/share/doc/lsb-base/copyright                                              > lsb-base.txt                       
cat /usr/share/doc/libnsl2/copyright                                               > libnsl2.txt                        
cat /usr/share/doc/libp11-kit0/copyright                                           > libp11-kit0.txt                    
cat /usr/share/doc/diffutils/copyright                                             > diffutils.txt                      
cat /usr/share/doc/findutils/copyright                                             > findutils.txt                      
cat /usr/share/doc/init-system-helpers/copyright                                   > init-system-helpers.txt            
cat /usr/share/doc/libblkid1/copyright                                             > libblkid1.txt                      
cat /usr/share/doc/libtinfo6/copyright                                             > libtinfo6.txt                      
cat /usr/share/doc/libgmp10/copyright                                              > libgmp10.txt                       
cat /usr/share/doc/sed/copyright                                                   > sed.txt                            
cat /usr/share/doc/libselinux1/copyright                                           > libselinux1.txt                    
cat /usr/share/doc/dash/copyright                                                  > dash.txt                           
cat /usr/share/doc/libacl1/copyright                                               > libacl1.txt                        
cat /usr/share/doc/gzip/copyright                                                  > gzip.txt                           
cat /usr/share/doc/libpcre3/copyright                                              > libpcre3.txt                       
cat /usr/share/doc/libpam-modules/copyright                                        > libpam-modules.txt                 
cat /usr/share/doc/logsave/copyright                                               > logsave.txt                        
cat /usr/share/doc/debianutils/copyright                                           > debianutils.txt                    
cat /usr/share/doc/debconf/copyright                                               > debconf.txt                        
cat /usr/share/doc/libattr1/copyright                                              > libattr1.txt                       
cat /usr/share/doc/base-files/copyright                                            > base-files.txt                     
cat /usr/share/doc/libpcre2-8-0/copyright                                          > libpcre2-8-0.txt                   
cat /usr/share/doc/libpam-modules-bin/copyright                                    > libpam-modules-bin.txt             
cat /usr/share/doc/libcom-err2/copyright                                           > libcom-err2.txt                    
cat /usr/share/doc/bash/copyright                                                  > bash.txt                           
cat /usr/share/doc/libtirpc-common/copyright                                       > libtirpc-common.txt                
cat /usr/share/doc/libkrb5-3/copyright                                             > libkrb5-3.txt                      
cat /usr/share/doc/libss2/copyright                                                > libss2.txt                         
cat /usr/share/doc/libtirpc3/copyright                                             > libtirpc3.txt                      
cat /usr/share/doc/libaudit1/copyright                                             > libaudit1.txt                      
cat /usr/share/doc/libkrb5support0/copyright                                       > libkrb5support0.txt                
cat /usr/share/doc/hostname/copyright                                              > hostname.txt                       
cat /usr/share/doc/gpgv/copyright                                                  > gpgv.txt                           
cat /usr/share/doc/libdebconfclient0/copyright                                     > libdebconfclient0.txt              
cat /usr/share/doc/adduser/copyright                                               > adduser.txt                        
cat /usr/share/doc/debian-archive-keyring/copyright                                > debian-archive-keyring.txt         
cat /usr/share/doc/libcrypt1/copyright                                             > libcrypt1.txt                      
cat /usr/share/doc/libmount1/copyright                                             > libmount1.txt                      
cat /usr/share/doc/libuuid1/copyright                                              > libuuid1.txt                       
cat /usr/share/doc/libsystemd0/copyright                                           > libsystemd0.txt                    
cat /usr/share/doc/libapt-pkg6.0/copyright                                         > libapt-pkg6.0.txt                  
cat /usr/share/doc/zlib1g/copyright                                                > zlib1g.txt                         
cat /usr/share/doc/libsemanage1/copyright                                          > libsemanage1.txt                   
cat /usr/share/doc/libzstd1/copyright                                              > libzstd1.txt                       
cat /usr/share/doc/mawk/copyright                                                  > mawk.txt                           
cat /usr/share/doc/libdb5.3/copyright                                              > libdb5.3.txt                       
cat /usr/share/doc/libtasn1-6/copyright                                            > libtasn1-6.txt                     
cat /usr/share/doc/perl-base/copyright                                             > perl-base.txt                      
cat /usr/share/doc/libseccomp2/copyright                                           > libseccomp2.txt                    
cat /usr/share/doc/libidn2-0/copyright                                             > libidn2-0.txt                      
cat /usr/share/doc/libnettle8/copyright                                            > libnettle8.txt                     
cat /usr/share/doc/libc-bin/copyright                                              > libc-bin.txt                       
cat /usr/share/doc/perl/copyright                                                  > perl.txt                           
cat /usr/share/doc/tar/copyright                                                   > tar.txt                            
cat /usr/share/doc/gcc-10-base/copyright                                           > gcc-10-base.txt                    
cat /usr/share/doc/libsepol1/copyright                                             > libsepol1.txt                      
cat /usr/share/doc/libext2fs2/copyright                                            > libext2fs2.txt                     
cat /usr/share/doc/ncurses-bin/copyright                                           > ncurses-bin.txt                    
cat /usr/share/doc/tzdata/copyright                                                > tzdata.txt                         
cat /usr/share/doc/e2fsprogs/copyright                                             > e2fsprogs.txt                      
cat /usr/share/doc/passwd/copyright                                                > passwd.txt                         
cat /usr/share/doc/grep/copyright                                                  > grep.txt                           
cat /usr/share/doc/libssl1.1/copyright                                             > libssl1.1.txt                      
cat /usr/share/doc/ncurses-base/copyright                                          > ncurses-base.txt                   
cat /usr/share/doc/liblzma5/copyright                                              > liblzma5.txt                       
cat /usr/share/doc/libsemanage-common/copyright                                    > libsemanage-common.txt             
cat /usr/share/doc/libgcrypt20/copyright                                           > libgcrypt20.txt                    
cat /usr/share/doc/libgssapi-krb5-2/copyright                                      > libgssapi-krb5-2.txt               
cat /usr/share/doc/libaudit-common/copyright                                       > libaudit-common.txt                
cat /usr/share/doc/libxxhash0/copyright                                            > libxxhash0.txt                     
cat /usr/share/doc/util-linux/copyright                                            > util-linux.txt                     
cat /usr/share/doc/libk5crypto3/copyright                                          > libk5crypto3.txt                   
cat /usr/share/doc/mount/copyright                                                 > mount.txt                          
cat /usr/share/doc/coreutils/copyright                                             > coreutils.txt                      
cat /usr/share/doc/dpkg/copyright                                                  > dpkg.txt                           
cat /usr/share/doc/libsmartcols1/copyright                                         > libsmartcols1.txt                  
cat /usr/share/doc/libudev1/copyright                                              > libudev1.txt                       
cat /usr/share/doc/liblz4-1/copyright                                              > liblz4-1.txt                       
cat /usr/share/doc/login/copyright                                                 > login.txt                          
cat /usr/share/doc/gcc-9-base/copyright                                            > gcc-9-base.txt                     
cat /usr/share/doc/apt/copyright                                                   > apt.txt                            
cat /usr/share/doc/libgnutls30/copyright                                           > libgnutls30.txt                    
cat /usr/share/doc/libunistring2/copyright                                         > libunistring2.txt                  
cat /usr/share/doc/libbz2-1.0/copyright                                            > libbz2-1.0.txt                     
cat /usr/share/doc/libc6/copyright                                                 > libc6.txt                          
cat /usr/share/doc/libgpg-error0/copyright                                         > libgpg-error0.txt                  
cat /usr/share/doc/libcap-ng0/copyright                                            > libcap-ng0.txt                     
cat /usr/share/doc/libhogweed6/copyright                                           > libhogweed6.txt                    
cat /usr/share/doc/sysvinit-utils/copyright                                        > sysvinit-utils.txt                 
cat /usr/share/doc/bsdutils/copyright                                              > bsdutils.txt                       
cat /usr/share/doc/libffi7/copyright                                               > libffi7.txt                        
cat /usr/share/doc/libkeyutils1/copyright                                          > libkeyutils1.txt                   
cat /usr/share/doc/autoconf/copyright                                              > autoconf.txt                       
cat /usr/share/doc/python3-distutils/copyright                                     > python3-distutils.txt              
cat /usr/share/doc/libyaml-dev/copyright                                           > libyaml-dev.txt                    
cat /usr/share/doc/libc6-dev/copyright                                             > libc6-dev.txt                      
cat /usr/share/doc/librsvg2-dev/copyright                                          > librsvg2-dev.txt                   
cat /usr/share/doc/libtiff5/copyright                                              > libtiff5.txt                       
cat /usr/share/doc/librsvg2-2/copyright                                            > librsvg2-2.txt                     
cat /usr/share/doc/libevent-core-2.1-7/copyright                                   > libevent-core-2.1-7.txt            
cat /usr/share/doc/libmagickcore-6.q16-6-extra/copyright                           > libmagickcore-6.q16-6-extra.txt    
cat /usr/share/doc/libpcre32-3/copyright                                           > libpcre32-3.txt                    
cat /usr/share/doc/libice6/copyright                                               > libice6.txt                        
cat /usr/share/doc/cpp/copyright                                                   > cpp.txt                            
cat /usr/share/doc/libpq5/copyright                                                > libpq5.txt                         
cat /usr/share/doc/libheif1/copyright                                              > libheif1.txt                       
cat /usr/share/doc/zlib1g-dev/copyright                                            > zlib1g-dev.txt                     
cat /usr/share/doc/libexif12/copyright                                             > libexif12.txt                      
cat /usr/share/doc/libevent-dev/copyright                                          > libevent-dev.txt                   
cat /usr/share/doc/libmount-dev/copyright                                          > libmount-dev.txt                   
cat /usr/share/doc/xz-utils/copyright                                              > xz-utils.txt                       
cat /usr/share/doc/libsqlite3-dev/copyright                                        > libsqlite3-dev.txt                 
cat /usr/share/doc/libx11-6/copyright                                              > libx11-6.txt                       
cat /usr/share/doc/liblcms2-dev/copyright                                          > liblcms2-dev.txt                   
cat /usr/share/doc/autotools-dev/copyright                                         > autotools-dev.txt                  
cat /usr/share/doc/libpcre2-dev/copyright                                          > libpcre2-dev.txt                   
cat /usr/share/doc/libxcb-render0/copyright                                        > libxcb-render0.txt                 
cat /usr/share/doc/libpango-1.0-0/copyright                                        > libpango-1.0-0.txt                 
cat /usr/share/doc/pkg-config/copyright                                            > pkg-config.txt                     
cat /usr/share/doc/fonts-dejavu-core/copyright                                     > fonts-dejavu-core.txt              
cat /usr/share/doc/libgdk-pixbuf-2.0-dev/copyright                                 > libgdk-pixbuf-2.0-dev.txt          
cat /usr/share/doc/libgssrpc4/copyright                                            > libgssrpc4.txt                     
cat /usr/share/doc/libctf-nobfd0/copyright                                         > libctf-nobfd0.txt                  
cat /usr/share/doc/libxau6/copyright                                               > libxau6.txt                        
cat /usr/share/doc/uuid-dev/copyright                                              > uuid-dev.txt                       
cat /usr/share/doc/libopenjp2-7/copyright                                          > libopenjp2-7.txt                   
cat /usr/share/doc/libxcb1-dev/copyright                                           > libxcb1-dev.txt                    
cat /usr/share/doc/libx265-192/copyright                                           > libx265-192.txt                    
cat /usr/share/doc/libltdl7/copyright                                              > libltdl7.txt                       
cat /usr/share/doc/libkadm5clnt-mit12/copyright                                    > libkadm5clnt-mit12.txt             
cat /usr/share/doc/libgirepository-1.0-1/copyright                                 > libgirepository-1.0-1.txt          
cat /usr/share/doc/libgmpxx4ldbl/copyright                                         > libgmpxx4ldbl.txt                  
cat /usr/share/doc/libglib2.0-dev-bin/copyright                                    > libglib2.0-dev-bin.txt             
cat /usr/share/doc/libbrotli-dev/copyright                                         > libbrotli-dev.txt                  
cat /usr/share/doc/libjpeg62-turbo/copyright                                       > libjpeg62-turbo.txt                
cat /usr/share/doc/automake/copyright                                              > automake.txt                       
cat /usr/share/doc/libcairo2-dev/copyright                                         > libcairo2-dev.txt                  
cat /usr/share/doc/libpixman-1-dev/copyright                                       > libpixman-1-dev.txt                
cat /usr/share/doc/libfontconfig-dev/copyright                                     > libfontconfig-dev.txt              
cat /usr/share/doc/libtiffxx5/copyright                                            > libtiffxx5.txt                     
cat /usr/share/doc/libselinux1-dev/copyright                                       > libselinux1-dev.txt                
cat /usr/share/doc/gir1.2-rsvg-2.0/copyright                                       > gir1.2-rsvg-2.0.txt                
cat /usr/share/doc/libgraphite2-3/copyright                                        > libgraphite2-3.txt                 
cat /usr/share/doc/xorg-sgml-doctools/copyright                                    > xorg-sgml-doctools.txt             
cat /usr/share/doc/libde265-0/copyright                                            > libde265-0.txt                     
cat /usr/share/doc/default-libmysqlclient-dev/copyright                            > default-libmysqlclient-dev.txt     
cat /usr/share/doc/libelf1/copyright                                               > libelf1.txt                        
cat /usr/share/doc/libtirpc-dev/copyright                                          > libtirpc-dev.txt                   
cat /usr/share/doc/libx11-dev/copyright                                            > libx11-dev.txt                     
cat /usr/share/doc/libxdmcp6/copyright                                             > libxdmcp6.txt                      
cat /usr/share/doc/libssl-dev/copyright                                            > libssl-dev.txt                     
cat /usr/share/doc/gir1.2-gdkpixbuf-2.0/copyright                                  > gir1.2-gdkpixbuf-2.0.txt           
cat /usr/share/doc/libevent-extra-2.1-7/copyright                                  > libevent-extra-2.1-7.txt           
cat /usr/share/doc/libevent-pthreads-2.1-7/copyright                               > libevent-pthreads-2.1-7.txt        
cat /usr/share/doc/libmagickcore-6.q16-dev/copyright                               > libmagickcore-6.q16-dev.txt        
cat /usr/share/doc/libwebpmux3/copyright                                           > libwebpmux3.txt                    
cat /usr/share/doc/libevent-openssl-2.1-7/copyright                                > libevent-openssl-2.1-7.txt         
cat /usr/share/doc/libicu-dev/copyright                                            > libicu-dev.txt                     
cat /usr/share/doc/libblkid-dev/copyright                                          > libblkid-dev.txt                   
cat /usr/share/doc/patch/copyright                                                 > patch.txt                          
cat /usr/share/doc/liblzma-dev/copyright                                           > liblzma-dev.txt                    
cat /usr/share/doc/libexif-dev/copyright                                           > libexif-dev.txt                    
cat /usr/share/doc/libmagickcore-6.q16-6/copyright                                 > libmagickcore-6.q16-6.txt          
cat /usr/share/doc/libdatrie1/copyright                                            > libdatrie1.txt                     
cat /usr/share/doc/libfreetype6/copyright                                          > libfreetype6.txt                   
cat /usr/share/doc/libc-dev-bin/copyright                                          > libc-dev-bin.txt                   
cat /usr/share/doc/libopenjp2-7-dev/copyright                                      > libopenjp2-7-dev.txt               
cat /usr/share/doc/libmagickwand-6.q16-6/copyright                                 > libmagickwand-6.q16-6.txt          
cat /usr/share/doc/bzip2/copyright                                                 > bzip2.txt                          
cat /usr/share/doc/comerr-dev/copyright                                            > comerr-dev.txt                     
cat /usr/share/doc/libjbig0/copyright                                              > libjbig0.txt                       
cat /usr/share/doc/libfftw3-double3/copyright                                      > libfftw3-double3.txt               
cat /usr/share/doc/libwebpdemux2/copyright                                         > libwebpdemux2.txt                  
cat /usr/share/doc/libkadm5srv-mit12/copyright                                     > libkadm5srv-mit12.txt              
cat /usr/share/doc/liblcms2-2/copyright                                            > liblcms2-2.txt                     
cat /usr/share/doc/libglib2.0-bin/copyright                                        > libglib2.0-bin.txt                 
cat /usr/share/doc/libdeflate-dev/copyright                                        > libdeflate-dev.txt                 
cat /usr/share/doc/libpixman-1-0/copyright                                         > libpixman-1-0.txt                  
cat /usr/share/doc/dpkg-dev/copyright                                              > dpkg-dev.txt                       
cat /usr/share/doc/libjpeg62-turbo-dev/copyright                                   > libjpeg62-turbo-dev.txt            
cat /usr/share/doc/libglib2.0-0/copyright                                          > libglib2.0-0.txt                   
cat /usr/share/doc/libpq-dev/copyright                                             > libpq-dev.txt                      
cat /usr/share/doc/libthai0/copyright                                              > libthai0.txt                       
cat /usr/share/doc/x11proto-dev/copyright                                          > x11proto-dev.txt                   
cat /usr/share/doc/file/copyright                                                  > file.txt                           
cat /usr/share/doc/libmariadb-dev/copyright                                        > libmariadb-dev.txt                 
cat /usr/share/doc/libxt-dev/copyright                                             > libxt-dev.txt                      
cat /usr/share/doc/icu-devtools/copyright                                          > icu-devtools.txt                   
cat /usr/share/doc/libharfbuzz0b/copyright                                         > libharfbuzz0b.txt                  
cat /usr/share/doc/libcairo-gobject2/copyright                                     > libcairo-gobject2.txt              
cat /usr/share/doc/libfontconfig1/copyright                                        > libfontconfig1.txt                 
cat /usr/share/doc/libpng16-16/copyright                                           > libpng16-16.txt                    
cat /usr/share/doc/libmaxminddb0/copyright                                         > libmaxminddb0.txt                  
cat /usr/share/doc/libmpc3/copyright                                               > libmpc3.txt                        
cat /usr/share/doc/libnuma1/copyright                                              > libnuma1.txt                       
cat /usr/share/doc/libdeflate0/copyright                                           > libdeflate0.txt                    
cat /usr/share/doc/libsepol1-dev/copyright                                         > libsepol1-dev.txt                  
cat /usr/share/doc/binutils-common/copyright                                       > binutils-common.txt                
cat /usr/share/doc/libyaml-0-2/copyright                                           > libyaml-0-2.txt                    
cat /usr/share/doc/imagemagick-6-common/copyright                                  > imagemagick-6-common.txt           
cat /usr/share/doc/libgdk-pixbuf2.0-bin/copyright                                  > libgdk-pixbuf2.0-bin.txt           
cat /usr/share/doc/libfribidi0/copyright                                           > libfribidi0.txt                    
cat /usr/share/doc/libthai-data/copyright                                          > libthai-data.txt                   
cat /usr/share/doc/xtrans-dev/copyright                                            > xtrans-dev.txt                     
cat /usr/share/doc/liblzo2-2/copyright                                             > liblzo2-2.txt                      
cat /usr/share/doc/hicolor-icon-theme/copyright                                    > hicolor-icon-theme.txt             
cat /usr/share/doc/libcairo-script-interpreter2/copyright                          > libcairo-script-interpreter2.txt   
cat /usr/share/doc/libpangocairo-1.0-0/copyright                                   > libpangocairo-1.0-0.txt            
cat /usr/share/doc/libopenexr-dev/copyright                                        > libopenexr-dev.txt                 
cat /usr/share/doc/libsigsegv2/copyright                                           > libsigsegv2.txt                    
cat /usr/share/doc/libjbig-dev/copyright                                           > libjbig-dev.txt                    
cat /usr/share/doc/libgdk-pixbuf2.0-common/copyright                               > libgdk-pixbuf2.0-common.txt        
cat /usr/share/doc/unzip/copyright                                                 > unzip.txt                          
cat /usr/share/doc/m4/copyright                                                    > m4.txt                             
cat /usr/share/doc/libdav1d4/copyright                                             > libdav1d4.txt                      
cat /usr/share/doc/libicu67/copyright                                              > libicu67.txt                       
cat /usr/share/doc/mariadb-common/copyright                                        > mariadb-common.txt                 
cat /usr/share/doc/libxrender1/copyright                                           > libxrender1.txt                    
cat /usr/share/doc/libpangoft2-1.0-0/copyright                                     > libpangoft2-1.0-0.txt              
cat /usr/share/doc/libpcre2-16-0/copyright                                         > libpcre2-16-0.txt                  
cat /usr/share/doc/libxml2/copyright                                               > libxml2.txt                        
cat /usr/share/doc/libilmbase25/copyright                                          > libilmbase25.txt                   
cat /usr/share/doc/gir1.2-glib-2.0/copyright                                       > gir1.2-glib-2.0.txt                
cat /usr/share/doc/libmariadb-dev-compat/copyright                                 > libmariadb-dev-compat.txt          
cat /usr/share/doc/libcairo2/copyright                                             > libcairo2.txt                      
cat /usr/share/doc/libxrender-dev/copyright                                        > libxrender-dev.txt                 
cat /usr/share/doc/libfreetype-dev/copyright                                       > libfreetype-dev.txt                
cat /usr/share/doc/fontconfig-config/copyright                                     > fontconfig-config.txt              
cat /usr/share/doc/librsvg2-common/copyright                                       > librsvg2-common.txt                
cat /usr/share/doc/libpcre3-dev/copyright                                          > libpcre3-dev.txt                   
cat /usr/share/doc/libxslt1-dev/copyright                                          > libxslt1-dev.txt                   
cat /usr/share/doc/libwmf-dev/copyright                                            > libwmf-dev.txt                     
cat /usr/share/doc/libsm6/copyright                                                > libsm6.txt                         
cat /usr/share/doc/libfreetype6-dev/copyright                                      > libfreetype6-dev.txt               
cat /usr/share/doc/python3-lib2to3/copyright                                       > python3-lib2to3.txt                
cat /usr/share/doc/libjpeg-dev/copyright                                           > libjpeg-dev.txt                    
cat /usr/share/doc/libopenexr25/copyright                                          > libopenexr25.txt                   
cat /usr/share/doc/libice-dev/copyright                                            > libice-dev.txt                     
cat /usr/share/doc/libfontconfig1-dev/copyright                                    > libfontconfig1-dev.txt             
cat /usr/share/doc/libilmbase-dev/copyright                                        > libilmbase-dev.txt                 
cat /usr/share/doc/libpcre2-32-0/copyright                                         > libpcre2-32-0.txt                  
cat /usr/share/doc/libxdmcp-dev/copyright                                          > libxdmcp-dev.txt                   
cat /usr/share/doc/libmagic1/copyright                                             > libmagic1.txt                      
cat /usr/share/doc/libexpat1-dev/copyright                                         > libexpat1-dev.txt                  
cat /usr/share/doc/fontconfig/copyright                                            > fontconfig.txt                     
cat /usr/share/doc/libgdk-pixbuf-2.0-0/copyright                                   > libgdk-pixbuf-2.0-0.txt            
cat /usr/share/doc/libkdb5-10/copyright                                            > libkdb5-10.txt                     
cat /usr/share/doc/libmariadb3/copyright                                           > libmariadb3.txt                    
cat /usr/share/doc/shared-mime-info/copyright                                      > shared-mime-info.txt               
cat /usr/share/doc/libxcb-shm0-dev/copyright                                       > libxcb-shm0-dev.txt                
cat /usr/share/doc/libsm-dev/copyright                                             > libsm-dev.txt                      
cat /usr/share/doc/libmaxminddb-dev/copyright                                      > libmaxminddb-dev.txt               
cat /usr/share/doc/libmpfr6/copyright                                              > libmpfr6.txt                       
cat /usr/share/doc/liblqr-1-0/copyright                                            > liblqr-1-0.txt                     
cat /usr/share/doc/make/copyright                                                  > make.txt                           
cat /usr/share/doc/libpcre16-3/copyright                                           > libpcre16-3.txt                    
cat /usr/share/doc/liblqr-1-0-dev/copyright                                        > liblqr-1-0-dev.txt                 
cat /usr/share/doc/libmagickwand-6.q16-dev/copyright                               > libmagickwand-6.q16-dev.txt        
cat /usr/share/doc/libx11-data/copyright                                           > libx11-data.txt                    
cat /usr/share/doc/libpng-dev/copyright                                            > libpng-dev.txt                     
cat /usr/share/doc/libwebp6/copyright                                              > libwebp6.txt                       
cat /usr/share/doc/libxau-dev/copyright                                            > libxau-dev.txt                     
cat /usr/share/doc/libcurl4-openssl-dev/copyright                                  > libcurl4-openssl-dev.txt           
cat /usr/share/doc/x11proto-xext-dev/copyright                                     > x11proto-xext-dev.txt              
cat /usr/share/doc/libgdbm-dev/copyright                                           > libgdbm-dev.txt                    
cat /usr/share/doc/libisl23/copyright                                              > libisl23.txt                       
cat /usr/share/doc/libxext-dev/copyright                                           > libxext-dev.txt                    
cat /usr/share/doc/libxml2-dev/copyright                                           > libxml2-dev.txt                    
cat /usr/share/doc/krb5-multidev/copyright                                         > krb5-multidev.txt                  
cat /usr/share/doc/imagemagick-6.q16/copyright                                     > imagemagick-6.q16.txt              
cat /usr/share/doc/libgmp-dev/copyright                                            > libgmp-dev.txt                     
cat /usr/share/doc/linux-libc-dev/copyright                                        > linux-libc-dev.txt                 
cat /usr/share/doc/libaom0/copyright                                               > libaom0.txt                        
cat /usr/share/doc/libnsl-dev/copyright                                            > libnsl-dev.txt                     
cat /usr/share/doc/libwmf0.2-7/copyright                                           > libwmf0.2-7.txt                    
cat /usr/share/doc/x11-common/copyright                                            > x11-common.txt                     
cat /usr/share/doc/libpcre2-posix2/copyright                                       > libpcre2-posix2.txt                
cat /usr/share/doc/libxslt1.1/copyright                                            > libxslt1.1.txt                     
cat /usr/share/doc/libpthread-stubs0-dev/copyright                                 > libpthread-stubs0-dev.txt          
cat /usr/share/doc/mysql-common/copyright                                          > mysql-common.txt                   
cat /usr/share/doc/libkrb5-dev/copyright                                           > libkrb5-dev.txt                    
cat /usr/share/doc/libtiff-dev/copyright                                           > libtiff-dev.txt                    
cat /usr/share/doc/libxcb-render0-dev/copyright                                    > libxcb-render0-dev.txt             
cat /usr/share/doc/libxcb-shm0/copyright                                           > libxcb-shm0.txt                    
cat /usr/share/doc/libxcb1/copyright                                               > libxcb1.txt                        
cat /usr/share/doc/libxext6/copyright                                              > libxext6.txt                       
cat /usr/share/doc/libxt6/copyright                                                > libxt6.txt                         
cat /usr/share/doc/libdjvulibre21/copyright                                        > libdjvulibre21.txt                 
cat /usr/share/doc/gir1.2-freedesktop/copyright                                    > gir1.2-freedesktop.txt             
cat /usr/share/doc/libdjvulibre-text/copyright                                     > libdjvulibre-text.txt              
cat /usr/share/doc/binutils/copyright                                              > binutils.txt                       
cat /usr/share/doc/libwebp-dev/copyright                                           > libwebp-dev.txt                    
cat /usr/share/doc/libglib2.0-data/copyright                                       > libglib2.0-data.txt                
cat /usr/share/doc/imagemagick/copyright                                           > imagemagick.txt                    
cat /usr/share/doc/libmagickcore-6-arch-config/copyright                           > libmagickcore-6-arch-config.txt    
cat /usr/share/doc/libglib2.0-dev/copyright                                        > libglib2.0-dev.txt                 
cat /usr/share/doc/libevent-2.1-7/copyright                                        > libevent-2.1-7.txt                 
cat /usr/share/doc/libdjvulibre-dev/copyright                                      > libdjvulibre-dev.txt               
cat /usr/share/doc/libdpkg-perl/copyright                                          > libdpkg-perl.txt                   
cat /usr/share/doc/libmagic-mgc/copyright                                          > libmagic-mgc.txt                   
cat /usr/share/doc/libtool/copyright                                               > libtool.txt                        
cat /usr/share/doc/libdb-dev/copyright                                             > libdb-dev.txt                      
cat /usr/share/doc/libpcrecpp0v5/copyright                                         > libpcrecpp0v5.txt                  
cat /usr/share/doc/libbsd0/copyright                                               > libbsd0.txt                        
cat /usr/share/doc/libpython3-stdlib/copyright                                     > libpython3-stdlib.txt              
cat /usr/share/doc/perl-modules-5.32/copyright                                     > perl-modules-5.32.txt              
cat /usr/share/doc/libprocps8/copyright                                            > libprocps8.txt                     
cat /usr/share/doc/libmd0/copyright                                                > libmd0.txt                         
cat /usr/share/doc/python3/copyright                                               > python3.txt                        
cat /usr/share/doc/sensible-utils/copyright                                        > sensible-utils.txt                 
cat /usr/share/doc/libgdbm-compat4/copyright                                       > libgdbm-compat4.txt                
cat /usr/share/doc/python3.9-minimal/copyright                                     > python3.9-minimal.txt              
cat /usr/share/doc/procps/copyright                                                > procps.txt                         
cat /usr/share/doc/ucf/copyright                                                   > ucf.txt                            
cat /usr/share/doc/libapr1/copyright                                               > libapr1.txt                        
cat /usr/share/doc/libmpdec3/copyright                                             > libmpdec3.txt                      
cat /usr/share/doc/openssh-client/copyright                                        > openssh-client.txt                 
cat /usr/share/doc/libaprutil1/copyright                                           > libaprutil1.txt                    
cat /usr/share/doc/python3-minimal/copyright                                       > python3-minimal.txt                
cat /usr/share/doc/libserf-1-1/copyright                                           > libserf-1-1.txt                    
cat /usr/share/doc/liberror-perl/copyright                                         > liberror-perl.txt                  
cat /usr/share/doc/mercurial-common/copyright                                      > mercurial-common.txt               
cat /usr/share/doc/media-types/copyright                                           > media-types.txt                    
cat /usr/share/doc/libexpat1/copyright                                             > libexpat1.txt                      
cat /usr/share/doc/subversion/copyright                                            > subversion.txt                     
cat /usr/share/doc/libperl5.32/copyright                                           > libperl5.32.txt                    
cat /usr/share/doc/libedit2/copyright                                              > libedit2.txt                       
cat /usr/share/doc/git-man/copyright                                               > git-man.txt                        
cat /usr/share/doc/libcurl3-gnutls/copyright                                       > libcurl3-gnutls.txt                
cat /usr/share/doc/python3.9/copyright                                             > python3.9.txt                      
cat /usr/share/doc/mercurial/copyright                                             > mercurial.txt                      
cat /usr/share/doc/libgdbm6/copyright                                              > libgdbm6.txt                       
cat /usr/share/doc/git/copyright                                                   > git.txt                            
cat /usr/share/doc/libsvn1/copyright                                               > libsvn1.txt                        
cat /usr/share/doc/libpython3.9-minimal/copyright                                  > libpython3.9-minimal.txt           
cat /usr/share/doc/libutf8proc2/copyright                                          > libutf8proc2.txt                   
cat /usr/share/doc/libcbor0/copyright                                              > libcbor0.txt                       
cat /usr/share/doc/libfido2-1/copyright                                            > libfido2-1.txt                     
cat /usr/share/doc/gpg-agent/copyright                                             > gpg-agent.txt                      
cat /usr/share/doc/libreadline8/copyright                                          > libreadline8.txt                   
cat /usr/share/doc/gnupg-l10n/copyright                                            > gnupg-l10n.txt                     
cat /usr/share/doc/dirmngr/copyright                                               > dirmngr.txt                        
cat /usr/share/doc/gnupg-utils/copyright                                           > gnupg-utils.txt                    
cat /usr/share/doc/readline-common/copyright                                       > readline-common.txt                
cat /usr/share/doc/gnupg/copyright                                                 > gnupg.txt                          
cat /usr/share/doc/libsqlite3-0/copyright                                          > libsqlite3-0.txt                   
cat /usr/share/doc/pinentry-curses/copyright                                       > pinentry-curses.txt                
cat /usr/share/doc/gpgconf/copyright                                               > gpgconf.txt                        
cat /usr/share/doc/gpg-wks-client/copyright                                        > gpg-wks-client.txt                 
cat /usr/share/doc/libksba8/copyright                                              > libksba8.txt                       
cat /usr/share/doc/gpg/copyright                                                   > gpg.txt                            
cat /usr/share/doc/gpgsm/copyright                                                 > gpgsm.txt                          
cat /usr/share/doc/libnpth0/copyright                                              > libnpth0.txt                       
cat /usr/share/doc/gpg-wks-server/copyright                                        > gpg-wks-server.txt                 
cat /usr/share/doc/libassuan0/copyright                                            > libassuan0.txt                     
cat /usr/share/doc/libnghttp2-14/copyright                                         > libnghttp2-14.txt                  
cat /usr/share/doc/libssh2-1/copyright                                             > libssh2-1.txt                      
cat /usr/share/doc/libsasl2-modules-db/copyright                                   > libsasl2-modules-db.txt            
cat /usr/share/doc/libpsl5/copyright                                               > libpsl5.txt                        
cat /usr/share/doc/libbrotli1/copyright                                            > libbrotli1.txt                     
cat /usr/share/doc/libcurl4/copyright                                              > libcurl4.txt                       
cat /usr/share/doc/netbase/copyright                                               > netbase.txt                        
cat /usr/share/doc/curl/copyright                                                  > curl.txt                           
cat /usr/share/doc/wget/copyright                                                  > wget.txt                           
cat /usr/share/doc/openssl/copyright                                               > openssl.txt                        
cat /usr/share/doc/libsasl2-2/copyright                                            > libsasl2-2.txt                     
cat /usr/share/doc/librtmp1/copyright                                              > librtmp1.txt                       
cat /usr/share/doc/ca-certificates/examples/ca-certificates-local/debian/copyright > ca-certificates-debian.txt         
cat /usr/share/doc/ca-certificates/copyright                                       > ca-certificates.txt                
cat /usr/share/doc/libldap-2.4-2/copyright                                         > libldap-2.4-2.txt
